# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  webui:
    image: webui
    build:
      context: .
      dockerfile: web.ui/Dockerfile
    ports:
      - 5000:80

  webapi:
    image: webapi
    build:
      context: .
      dockerfile: web.api/Dockerfile
    ports:
      - 5024:80
